format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$cmd_duration\
$fill\
$time\
$line_break\
$lua\
$jobs\
$battery\

$status\
$character
"""
add_newline = false

[character]
success_symbol = "[λ](bold cyan) "
error_symbol = "[λ](bold red) "
vicmd_symbol = "[ ](bold purple)"

[username]
style_user = "fg:bold italic #F28FAD"
show_always = true
format = "[Vicenzo]($style) "

[directory]
truncation_length = 10
truncate_to_repo = false
style = "bold  #C3DBC5 bg:#643FFF"
format = "[:: ](bold #b7bdf8)[$path ]($style)[$read_only]($read_only_style) "

[time]
time_format = "%I:%M%P_%b-%d"
format = "[$time]($style)"
style = 'bold #b7bdf8'
disabled = false

[nodejs]
symbol = " "

[fill]
style = 'italic bold #00ffd0'
